version: "3.8"
services:
  php:
    build:
      context: './php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./Apis:/var/www/html/
    container_name: php
  
  apache:
    build:
      context: './apache/'
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - ./Apis:/var/www/html/
    container_name: apache
  
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "php_app_db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    container_name: mariadb

volumes:
  data:
