version: '3.2'
services:
  php-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"
  # phpmyadmin:
  #   image: phpmyadmin
  #   container_name: phpmyadmin
  #   links:
  #     - mariadb
  #   environment:
  #     PMA_HOST: mariadb
  #   restart: always
  #   ports:
  #     - 8081:80